postgresql:
  image: sameersbn/postgresql:9.4
  environment:
    - DB_USER=redmine
    - DB_PASS=secretpassword
    - DB_NAME=redmine_production
  volumes:
    - /srv/docker/redmine/postgresql:/var/lib/postgresql
redmine:
  image: sameersbn/redmine:3.0.3
  links:
    - postgresql:postgresql
  environment:
    - TZ=Asia/Kolkata
    - REDMINE_PORT=10083
    - SMTP_ENABLED=false
    - SMTP_DOMAIN=www.example.com
    - SMTP_HOST=smtp.gmail.com
    - SMTP_PORT=587
    - SMTP_USER=mailer@example.com
    - SMTP_PASS=password
    - SMTP_STARTTLS=true
    - SMTP_AUTHENTICATION=:login
  ports:
    - "10083:80"
  volumes:
    - /srv/docker/redmine/redmine:/home/redmine/data
